### ISSUE TITLE
Ubuntu install with erros "configure: error: BLAS was specified but not available"

### ISSUE THREAD

**Issue by shanexuuu** [astanabe/ClaidentInstaller#1]
Hi thanks for developling this tool. 

I tried to install Claident (installClaident_Debian.sh) on our Ubuntu 20.04.6 and Ubuntu 22.04.3. However both of them say"configure: error: BLAS was specified but not available" and then stopped.
![Claident install error_screenshot](https://github.com/astanabe/ClaidentInstaller/assets/113850758/b6ce450b-ebcc-4fa1-b9e4-780a91ca524a)

I thought this is related to BLAST. So I mannually installed BLAST and put blastp etc. into "bin/" file. But this configure error still exists.

Could you give me any suggestion?

Thanks!

**Comment by astanabe** [comment]
Sorry, this is a bug.
This bug has been fixed today.

BLAS is not BLAST.
BLAS is the most famous linear algebra library.

**Comment by shanexuuu** [comment]
I see. Thank you very much!
________________________________

**Comment by astanabe** [comment]
I found that several important required R packages has been updated to incompatible version.
Therefore, I updated to bundled R-4.2.3 to R-4.3.3.
Please update installer again.
This finding depends on your report.
Thank you.
